# Generated by Django 3.0.3 on 2020-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('apellidoPaterno', models.CharField(max_length=254)),
                ('apellidoMaterno', models.CharField(max_length=254)),
                ('ciudad', models.CharField(max_length=254, null=True)),
                ('estado', models.CharField(max_length=254, null=True)),
                ('genero', models.CharField(max_length=254, null=True)),
                ('estadoCivil', models.CharField(max_length=254, null=True)),
            ],
        ),
    ]
