# Generated by Django 3.0.3 on 2020-02-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_ciudad_estado_estadocivil_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='estadoCivil',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='genero',
        ),
        migrations.AddField(
            model_name='registro',
            name='Ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registro.Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='Estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registro.Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='EstadoCivil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registro.EstadoCivil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='Genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registro.Genero'),
            preserve_default=False,
        ),
    ]
