# Generated by Django 3.0.3 on 2020-02-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_modelregistro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Profile',
        ),
    ]
