# Generated by Django 3.0.3 on 2020-02-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20200213_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelRegistro',
        ),
    ]
