# Generated by Django 3.0.3 on 2020-02-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_delete_modelregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
