# Generated by Django 3.0.3 on 2020-02-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumnoMateria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='genero',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.IntegerField(),
        ),
    ]
